# Generated by Django 5.1.4 on 2024-12-15 11:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('Dob', models.DateField()),
                ('profile_picture', models.ImageField(default='default.jpg', upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(default='SEEL.jpg', upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='HealthMetricType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('cell', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_present', models.PositiveIntegerField(default=0, verbose_name='Total Days Present')),
                ('total_absent', models.PositiveIntegerField(default=0, verbose_name='Total Days Absent')),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summary', to='irereroapp.child')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='irereroapp.class'),
        ),
        migrations.CreateModel(
            name='HealthMetricRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='irereroapp.child')),
                ('metric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='irereroapp.healthmetrictype')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Headteacher', 'Headteacher'), ('Teacher', 'Teacher'), ('Parent', 'Parent')], max_length=50)),
                ('phonenumber', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='irereroapp.school')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('cell', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irereroapp.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='irereroapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='ParentsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=255)),
                ('child_dob', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irereroapp.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='irereroapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='irereroapp.user'),
        ),
        migrations.AddField(
            model_name='child',
            name='guardian',
            field=models.ForeignKey(limit_choices_to={'role': 'Parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='irereroapp.user'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Attendance Date')),
                ('is_present', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='irereroapp.child')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date'],
                'unique_together': {('child', 'date')},
            },
        ),
    ]
