# Generated by Django 5.1.4 on 2024-12-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irereroapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesummary',
            name='child',
        ),
        migrations.RemoveField(
            model_name='child',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='child',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='healthmetricrecord',
            name='child',
        ),
        migrations.RemoveField(
            model_name='healthmetricrecord',
            name='metric_type',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='AttendanceSummary',
        ),
        migrations.DeleteModel(
            name='child',
        ),
        migrations.DeleteModel(
            name='HealthMetricRecord',
        ),
    ]
