# Generated by Django 5.1.4 on 2024-12-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irereroapp', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
