# Generated by Django 5.1.4 on 2024-12-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irereroapp', '0005_alter_class_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ManyToManyField(limit_choices_to={'role': 'Teacher'}, related_name='classes', to='irereroapp.user'),
        ),
    ]
